### PR TITLE
yarn alias support

### PR DESCRIPTION
**Pull request by danitt**
hi mate,

tweaked the repo a little to allow adding this as a dependency which is treated the same as the official "@types/*" dependencies.

so you can import it like:
`yarn add @types/jsrsasign@git+https://git@github.com/ffflorian/jsrsasign-types.git`

it appears in your package.json as:
```
  "dependencies": {
    "@types/jsrsasign": "git+https://git@github.com/ffflorian/jsrsasign-types.git",
   ...
  },
```

and it then gets automatically read by TS just like any other official typing ☀️

### CODE REVIEW

**Comment by ffflorian** [comment]
Hi @danitt, that's a great idea, thanks! Looks good so far but I noticed that you changed the style of all TypeScript files. I am wondering why the actions did not run on your PR, they should've told us that the style is incorrect.

**Comment by ffflorian** [comment]
Could you please merge from master and we'll see if the GitHub actions run?

**Comment by danitt** [comment]
@ffflorian I ran the "yarn lint" and "yarn prettier" tasks before committing, I believe one of those kicked off the reformatting

**Comment by ffflorian** [comment]
@danitt oh I see :smiley:

**Comment by ffflorian** [comment]
Thanks!

**Pull request merged**
